name: PyPI release

on:
  # For Github release-based publishing
  #release:
  #  types: [published]
  # For tag-based (instead of Github-specific release-based):
  push:
    tags:
      - '*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
    permissions:
      contents: read
      name: pypi
      url: https://pypi.org/p/sphinx-evita
    permissions:
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:

    - uses: actions/checkout@v5
    
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: 3.11
    
    - name: Build package distributions
      run: uv build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1